version: "{build}"

clone_depth: 1

environment:
  CFSSL_VERSION: 1.3.2
  GOPATH: C:\gopath
  GOROOT: C:\go110

install:
  - mkdir %GOPATH%\src\github.com\cloudflare
  - cd %GOPATH%\src\github.com\cloudflare
  - git clone --depth 1 -b %CFSSL_VERSION% https://github.com/cloudflare/cfssl.git
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%GOROOT%\bin;%PATH%;
  - go version
  - go env

build_script:
  - cd cfssl\cmd\cfssl
  - go build -v -o %APPVEYOR_BUILD_FOLDER%\cfssl.exe

artifacts:
  - path: cfssl.exe
    name: CFSSL binary
