version: "{build}"

clone_depth: 1

environment:
  CFSSL_VERSION: 1.3.2
  GOPATH: C:\gopath
  GOROOT: C:\go110

install:
  - mkdir %GOPATH%\src\github.com\cloudflare
  - cd %GOPATH%\src\github.com\cloudflare
  - git clone --depth 1 -b %CFSSL_VERSION% https://github.com/cloudflare/cfssl.git
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%GOROOT%\bin;%PATH%;
  - go version
  - go env

before_build:
  - cd cfssl
  - ps: $env:GITCOMMIT_FULL = git rev-parse HEAD

build_script:
  - cd cmd\cfssl
  - go build -v -o %APPVEYOR_BUILD_FOLDER%\cfssl.exe
  - cd ..\cfssljson
  - go build -v -o %APPVEYOR_BUILD_FOLDER%\cfssljson.exe

after_build:
  - "%APPVEYOR_BUILD_FOLDER%\\cfssl.exe version"
  - 7z a %APPVEYOR_BUILD_FOLDER%\cfssl-v%CFSSL_VERSION%.7z %APPVEYOR_BUILD_FOLDER%\*.exe
  - ps: |
      $env:ARTIFACT_HASH = (Get-FileHash -Algorithm SHA256 $env:APPVEYOR_BUILD_FOLDER\cfssl-v$env:CFSSL_VERSION.7z).Hash
      "$env:ARTIFACT_HASH  cfssl-v$env:CFSSL_VERSION.7z" | Out-File -Encoding ascii -File $env:APPVEYOR_BUILD_FOLDER\sha256sum.txt

artifacts:
  - path: cfssl-v$(CFSSL_VERSION).7z
    name: CFSSL binary archive
  - path: sha256sum.txt
    name: SHA256 hash of CFSSL binary archive

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: |
      CFSSL binary for Windows 64-bit.

      Built https://github.com/cloudflare/cfssl at commit `$(GITCOMMIT_FULL)`.

      | File                       | SHA-256 sum |
      | ---                        | ---         |
      | cfssl-v$(CFSSL_VERSION).7z | `$(ARTIFACT_HASH)` |
    auth_token:
      secure: Jfjhx7TC03brqWcw+uUMXHJxj445SVeEcmSnDUV10ggRuU6UlzQMLSVGIBRqWD8v
    artifact: cfssl-v$(CFSSL_VERSION).7z,sha256sum.txt
    on:
      branch: master
      appveyor_repo_tag: true
