version: "{build}"

clone_depth: 1

environment:
  CFSSL_VERSION: 1.3.2
  GOPATH: C:\gopath
  GOROOT: C:\go110

install:
  - mkdir %GOPATH%\src\github.com\cloudflare
  - cd %GOPATH%\src\github.com\cloudflare
  - git clone --depth 1 -b %CFSSL_VERSION% https://github.com/cloudflare/cfssl.git
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%GOROOT%\bin;%PATH%;
  - go version
  - go env

build_script:
  - cd cfssl\cmd\cfssl
  - go build -v -o %APPVEYOR_BUILD_FOLDER%\cfssl.exe
  - cd ..\cfssljson
  - go build -v -o %APPVEYOR_BUILD_FOLDER%\cfssljson.exe

after_build:
  - "%APPVEYOR_BUILD_FOLDER%\\cfssl.exe version"
  - 7z a %APPVEYOR_BUILD_FOLDER%\cfssl.7z %APPVEYOR_BUILD_FOLDER%\*.exe
  - ps: |
      $env:ARTIFACT_HASH = (Get-FileHash -Algorithm SHA256 $env:APPVEYOR_BUILD_FOLDER\cfssl.7z).Hash
      $env:ARTIFACT_HASH | Out-File -Encoding utf8 -File $env:APPVEYOR_BUILD_FOLDER\cfssl.7z.sha256

artifacts:
  - path: cfssl.7z
    name: CFSSL binary archive
  - path: cfssl.7z.sha256
    name: SHA256 hash of CFSSL binary archive
